version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_bus
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bus_db
      MYSQL_USER: bus_user
      MYSQL_PASSWORD: bus_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
